dataset: "EB_Small"

path:
  corpus_path: "../Filtered_mini_dataset_v1/processed_merged_chunks/"
  lexicon_path: "../Filtered_mini_dataset_v1/eb_small_dictionary_mfa.txt"
  raw_path: "../Filtered_mini_dataset_v1/raw_data/EB_Small"
  preprocessed_path: "../Filtered_mini_dataset_v1/preprocessed_data/EB_Small"

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
